server:
  port: 8081
  error:
    include-message: always

# SPRING JPA
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keola_project
    username: postgres
    password: postgrespass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
