CREATE TABLE products
(
    id            UUID NOT NULL,
    creado_en     TIMESTAMP WITHOUT TIME ZONE,
    modificado_en TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    price         DOUBLE PRECISION,
    stock         DOUBLE PRECISION,
    usuario_id    UUID NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE roles
(
    rol_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_rol VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (rol_id)
);

CREATE TABLE users
(
    id               UUID         NOT NULL,
    creado_en        TIMESTAMP WITHOUT TIME ZONE,
    modificado_en    TIMESTAMP WITHOUT TIME ZONE,
    nombre_usuario   VARCHAR(20)  NOT NULL,
    apellido_usuario VARCHAR(20)  NOT NULL,
    username         VARCHAR(20)  NOT NULL,
    correo           VARCHAR(50)  NOT NULL,
    contrasena       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    rol_id     BIGINT NOT NULL,
    usuario_id UUID   NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (rol_id, usuario_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_correo UNIQUE (correo);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (rol_id) REFERENCES roles (rol_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (usuario_id) REFERENCES users (id);